<?php
$key = $_REQUEST['siteName'];

$Generar = generateConfigFiles($key,$key,0,0,0,1);

function generateConfigFiles($base,$sender,$renovar,$demo,$codigo,$tipo){

	$contenido = "<?php\n";
	$contenido .= "ini_set('display_errors', 0);";
	$contenido .= "\n";
	$contenido .= "ini_set('display_startup_errors', 0);";
	$contenido .= "\n";
	$contenido .= 'error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE);';
	$contenido .= "\n";
	$contenido .= 'define("_APP_NAME","MiPOS");';
	$contenido .= "\n";
	$contenido .= 'define("_APP_KEY","R3J1cG9NS1MyMDE2");';
	$contenido .= "\n";
	$contenido .= 'define("_PUBLIC_KEY","R3J1cG9NS1MyMDE2");';
	$contenido .= "\n";
	$contenido .= 'define("_PRIVATE_KEY","R3J1cG9NS1MyMDE2");';
	$contenido .= "\n";
	$contenido .= 'define("_DOMINIO_","'.$base.'.miSite.com");';
	$contenido .= "\n";
	$contenido .= 'define("_DOMINIO_SSL","https://'.$base.'.miSite.com/");';
	$contenido .= "\n";
	$contenido .= 'define("_DOMINIO_TIENDA","https://'.$base.'.miSite.com/");';
	$contenido .= "\n";
	$contenido .= 'define("_DOMINIO_PUBLICO_","'.$base.'.miSite.com");';
	$contenido .= "\n";
	$contenido .= 'define("_DOMAIN_KEY","d3d3LmRlbnRpc3Rhc2Nvc3RhcmljYS5jb20=");';
	$contenido .= "\n";
	$contenido .= 'define("_EMAILRECEPCION_","'.$base.'@miSite.com");';
	$contenido .= "\n";
	$contenido .= 'define("_CODIGO","'.$codigo.'");';
	$contenido .= "\n";
	$contenido .= 'define("_SENDER","'.$sender.'");';
	$contenido .= "\n";
	$contenido .= 'define("_ISDEMO","'.$demo.'");';
	$contenido .= "\n";
	$contenido .= 'define("_DEVMODE","0");';
	$contenido .= "\n";
	$contenido .= 'define("_PERMITE_AGREGAR","'.$tipo.'");';
	$contenido .= "\n";
	$contenido .= 'define("_EXPIRA","'.$renovar.'");';
	$contenido .= "\n";
	$contenido .= 'define("_RUTA_PUBLICO_","/home/wwwroot/'.$base.'.miSite.com/");';
	$contenido .= "\n";
	$contenido .= '/* VERSION */';
	$contenido .= "\n";
	$contenido .= 'define("_ISTIPO","'.$tipo.'");';
	$contenido .= "\n";
	$contenido .= '/* RECEPCION AUTOMATICA */';
	$contenido .= "\n";
	$contenido .= 'define("_IMAP_EMAIL","'.$base.'@miSite.com");';
	$contenido .= "\n";
	$contenido .= 'define("_IMAP_PASS","m123345567");';
	$contenido .= "\n";
	$contenido .= 'define("_IMAP_SERVER","mail.miSite.com");';
	$contenido .= "\n";
	$contenido .= 'define("_IMAP_PORT","993");';
	$contenido .= "\n";
	$contenido .= 'define("_IMAP_INBOX","/imap/ssl/novalidate-cert}INBOX");';
	$contenido .= "\n";
	$contenido .= '/* CONFIGURACIONES POR DEFECTO */';
	$contenido .= "\n";
	$contenido .= 'define("_DEFAULT_LANGUAGE", "es");';
	$contenido .= "\n";
	$contenido .= '$cookie_time = (3600 * 24 * 30); // 30 days';
	$contenido .= "\n";
	$contenido .= '$cookie_name = "userSessionValue";';
	$contenido .= "\n";
	$contenido .= '/* CONFIGURACIONES POR DEFECTO */';
	$contenido .= "\n";
	$contenido .= '/* INCLUDES */';
	$contenido .= "\n";
	$contenido .= '/* CONFIGURACION BASE DE DATOS */';
	$contenido .= "\n";
	$contenido .= 'include($_SERVER[\'DOCUMENT_ROOT\']."/includes/dbConfig.php");';
	$contenido .= "\n";
	$contenido .= '/* CONFIGURACION BASE DE DATOS */';
	$contenido .= "\n";
	$contenido .= '/* CLASE CONEXION BASE DE DATOS */';
	$contenido .= "\n";
	$contenido .= 'include($_SERVER[\'DOCUMENT_ROOT\']."/includes/clases/clase.conexion.php");';
	$contenido .= "\n";
	$contenido .= '/* CLASE CONEXION BASE DE DATOS */';
	$contenido .= "\n";
	$contenido .= '/* FUNCIONES */';
	$contenido .= "\n";
	$contenido .= 'include($_SERVER[\'DOCUMENT_ROOT\']."/includes/clases/numeroletra.php");';
	$contenido .= "\n";
	$contenido .= 'include($_SERVER[\'DOCUMENT_ROOT\']."/includes/funciones.php");';
	$contenido .= "\n";
	$contenido .= '/* IDIOMA */';
	$contenido .= "\n";
	$contenido .= 'include($_SERVER[\'DOCUMENT_ROOT\']."/includes/idiomas/"._DEFAULT_LANGUAGE.".php");';
	$contenido .= "\n";
	$contenido .= '/* INCLUDES */';
	$contenido .= "\n";
	$contenido .= '/* Extraer Valores */';
	$contenido .= "\n";
	$contenido .= '$action = $_REQUEST[\'accion\'];';
	$contenido .= "\n";
	$contenido .= '$cmd = $_REQUEST[\'cmd\'];';
	$contenido .= "\n";
	$contenido .= '$act= $_REQUEST[\'act\'];';
	$contenido .= "\n";
	$contenido .= '$date = $_REQUEST[\'date\'];';
	$contenido .= "\n";
	$contenido .= '/* Extraer Valores */';
	$contenido .= "\n";
	$contenido .= 'if (isset($_SERVER[\'HTTP_CF_VISITOR\'])) {';
	$contenido .= "\n";
    $contenido .= 'if (preg_match(\'/https/i\', $_SERVER[\'HTTP_CF_VISITOR\'])) {';
	$contenido .= "\n";
	$contenido .= '$_SERVER[\'HTTPS\'] = \'On\';';
	$contenido .= "\n";
	$contenido .= '$_SERVER[\'HTTP_X_FORWARDED_PORT\'] = 443;';
	$contenido .= "\n";
	$contenido .= '$_SERVER[\'SERVER_PORT\'] = 443;';
	$contenido .= "\n";
	$contenido .= '}';
	$contenido .= "\n";
	$contenido .= '}';
	$contenido .= "\n";
	$contenido .= '$puerto = $_SERVER[\'SERVER_PORT\'];';
	$contenido .= "\n";
	$contenido .= "\n?>";

$archivo="/home/wwwroot/".$base.".miSite.com/includes/configuracion.php";

$fp=fopen($archivo,'w');
fwrite($fp,$contenido);
fclose($fp);


$dbconfig = "<?php\n";
	$dbconfig .= 'define(\'_DBSERVER\',\'127.0.0.1\');';
	$dbconfig .= "\n";
	$dbconfig .= 'define(\'_DBUSER\',\'mipos_'.$base.'\');';
	$dbconfig .= "\n";
	$dbconfig .= 'define(\'_DBPASS\',\'HR2TjnPmbRx2HMXH\');';
	$dbconfig .= "\n";
	$dbconfig .= 'define(\'_DBNAME\',\'mipos_'.$base.'\');';
	$dbconfig .= "\n";
	
	$dbconfig .= 'define(\'_UPLOAD_DIR\',\'/home/wwwroot/'.$base.'.miSite.com/\');';
	$dbconfig .= "\n";
	$dbconfig .= "\n?>";
$archivoConfig="/home/wwwroot/".$base.".miSite.com/includes/dbConfig.php";

$fp=fopen($archivoConfig,'w+');
fwrite($fp,$dbconfig);
fclose($fp);

return true;
}